server:
  port: 9000
  servlet:
    context-path: /

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  application:
    name: dubbo-access

logging:
  level:
    cn.alex: debug
  pattern:
    dateformat: HH::mm:ss:SSS